//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTasks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTasks.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string AboutContactUs {
            get {
                return ResourceManager.GetString("AboutContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for {0} {1}.
        /// </summary>
        public static string AboutEmailSubject {
            get {
                return ResourceManager.GetString("AboutEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string AboutRateReview {
            get {
                return ResourceManager.GetString("AboutRateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate.
        /// </summary>
        public static string AppBarActivate {
            get {
                return ResourceManager.GetString("AppBarActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add bullet.
        /// </summary>
        public static string AppBarAddBullet {
            get {
                return ResourceManager.GetString("AppBarAddBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarAddSubtask {
            get {
                return ResourceManager.GetString("AppBarAddSubtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string AppBarComplete {
            get {
                return ResourceManager.GetString("AppBarComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete all.
        /// </summary>
        public static string AppBarCompleteAllSubtasks {
            get {
                return ResourceManager.GetString("AppBarCompleteAllSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AppBarDelete {
            get {
                return ResourceManager.GetString("AppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all tasks.
        /// </summary>
        public static string AppBarDeleteAll {
            get {
                return ResourceManager.GetString("AppBarDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all.
        /// </summary>
        public static string AppBarDeleteAllSubtasks {
            get {
                return ResourceManager.GetString("AppBarDeleteAllSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete completed tasks.
        /// </summary>
        public static string AppBarDeleteCompleted {
            get {
                return ResourceManager.GetString("AppBarDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string AppBarDone {
            get {
                return ResourceManager.GetString("AppBarDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string AppBarNew {
            get {
                return ResourceManager.GetString("AppBarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string AppBarOk {
            get {
                return ResourceManager.GetString("AppBarOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string AppBarPin {
            get {
                return ResourceManager.GetString("AppBarPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin tile.
        /// </summary>
        public static string AppBarPinTile {
            get {
                return ResourceManager.GetString("AppBarPinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile settings.
        /// </summary>
        public static string AppBarTileSettings {
            get {
                return ResourceManager.GetString("AppBarTileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string AppBarUnpin {
            get {
                return ResourceManager.GetString("AppBarUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin tile.
        /// </summary>
        public static string AppBarUnpinTile {
            get {
                return ResourceManager.GetString("AppBarUnpinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up.
        /// </summary>
        public static string BackingUp {
            get {
                return ResourceManager.GetString("BackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup will create new folder &quot;{0}&quot;. You can move this folder to your location, but please, do not rename it. Also don&apos;t modify files inside.
        ///It&apos;s still in beta. If you have any problem, send us email..
        /// </summary>
        public static string BackupAndRestoreHelpText {
            get {
                return ResourceManager.GetString("BackupAndRestoreHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup &amp; restore.
        /// </summary>
        public static string BackupAndRestoreTitle {
            get {
                return ResourceManager.GetString("BackupAndRestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading list of backups.
        /// </summary>
        public static string BackupDownloadingList {
            get {
                return ResourceManager.GetString("BackupDownloadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        public static string BackupLatest {
            get {
                return ResourceManager.GetString("BackupLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful backup..
        /// </summary>
        public static string BackupOk {
            get {
                return ResourceManager.GetString("BackupOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupText {
            get {
                return ResourceManager.GetString("BackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bullet.
        /// </summary>
        public static string BulletText {
            get {
                return ResourceManager.GetString("BulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;4.3.0 &quot;: {
        ///        &quot;date&quot;: &quot;2014-09-04&quot;,
        ///        &quot;items&quot;: [
        ///            &quot;task count on main tile (you can hide it in settings)&quot;,
        ///            &quot;option to swap date and title on wide tile&quot;
        ///        ]
        ///    },
        ///    &quot;4.3.0&quot;: {
        ///        &quot;date&quot;: &quot;2014-09-04&quot;,
        ///        &quot;items&quot;: [
        ///            &quot;task count on main tile&quot;,
        ///            &quot;option to swap date and title on wide tile&quot;
        ///        ]
        ///    },
        ///    &quot;4.2.0&quot;: {
        ///        &quot;date&quot;: &quot;2014-08-30&quot;,
        ///        &quot;items&quot;: [
        ///            &quot;backup and restore (BETA)&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChangelogFile {
            get {
                return ResourceManager.GetString("ChangelogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE DATE.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE REMINDER.
        /// </summary>
        public static string ChooseReminderTime {
            get {
                return ResourceManager.GetString("ChooseReminderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE TIME.
        /// </summary>
        public static string ChooseTime {
            get {
                return ResourceManager.GetString("ChooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom due date.
        /// </summary>
        public static string DateCustomDue {
            get {
                return ResourceManager.GetString("DateCustomDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string DateLastMonth {
            get {
                return ResourceManager.GetString("DateLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last week.
        /// </summary>
        public static string DateLastWeek {
            get {
                return ResourceManager.GetString("DateLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string DateLater {
            get {
                return ResourceManager.GetString("DateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next month.
        /// </summary>
        public static string DateNextMonth {
            get {
                return ResourceManager.GetString("DateNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next week.
        /// </summary>
        public static string DateNextWeek {
            get {
                return ResourceManager.GetString("DateNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no due date.
        /// </summary>
        public static string DateNoDue {
            get {
                return ResourceManager.GetString("DateNoDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string DateOverdue {
            get {
                return ResourceManager.GetString("DateOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someday.
        /// </summary>
        public static string DateSomeday {
            get {
                return ResourceManager.GetString("DateSomeday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this month.
        /// </summary>
        public static string DateThisMonth {
            get {
                return ResourceManager.GetString("DateThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this week.
        /// </summary>
        public static string DateThisWeek {
            get {
                return ResourceManager.GetString("DateThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string DateTimeDaysAbbr {
            get {
                return ResourceManager.GetString("DateTimeDaysAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string DateTimeHoursAbbr {
            get {
                return ResourceManager.GetString("DateTimeHoursAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string DateTimeMinutesAbbr {
            get {
                return ResourceManager.GetString("DateTimeMinutesAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string DateToday {
            get {
                return ResourceManager.GetString("DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string DateTomorrow {
            get {
                return ResourceManager.GetString("DateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upcoming.
        /// </summary>
        public static string DateUpcoming {
            get {
                return ResourceManager.GetString("DateUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string DateYesterday {
            get {
                return ResourceManager.GetString("DateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string Days1 {
            get {
                return ResourceManager.GetString("Days1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string Days2To4 {
            get {
                return ResourceManager.GetString("Days2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string Days5AndMore {
            get {
                return ResourceManager.GetString("Days5AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DaysLabel {
            get {
                return ResourceManager.GetString("DaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all tasks?.
        /// </summary>
        public static string DeleteAllTasks {
            get {
                return ResourceManager.GetString("DeleteAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all tasks.
        /// </summary>
        public static string DeleteAllTasksCaption {
            get {
                return ResourceManager.GetString("DeleteAllTasksCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        public static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        public static string DeleteTaskCaption {
            get {
                return ResourceManager.GetString("DeleteTaskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DeleteTaskNo {
            get {
                return ResourceManager.GetString("DeleteTaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteTaskYes {
            get {
                return ResourceManager.GetString("DeleteTaskYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        public static string Hours1 {
            get {
                return ResourceManager.GetString("Hours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string Hours2To4 {
            get {
                return ResourceManager.GetString("Hours2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string Hours5AndMore {
            get {
                return ResourceManager.GetString("Hours5AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string HoursLabel {
            get {
                return ResourceManager.GetString("HoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        public static string Minutes1 {
            get {
                return ResourceManager.GetString("Minutes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string Minutes2To4 {
            get {
                return ResourceManager.GetString("Minutes2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string Minutes5AndMore {
            get {
                return ResourceManager.GetString("Minutes5AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string MinutesLabel {
            get {
                return ResourceManager.GetString("MinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} month.
        /// </summary>
        public static string Months1 {
            get {
                return ResourceManager.GetString("Months1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        public static string Months2To4 {
            get {
                return ResourceManager.GetString("Months2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backups.
        /// </summary>
        public static string NoBackups {
            get {
                return ResourceManager.GetString("NoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no reminder.
        /// </summary>
        public static string NoReminder {
            get {
                return ResourceManager.GetString("NoReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subtasks.
        /// </summary>
        public static string NoSubtasks {
            get {
                return ResourceManager.GetString("NoSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tasks.
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or text box bellow to add a task..
        /// </summary>
        public static string NoTasksHelpEnd {
            get {
                return ResourceManager.GetString("NoTasksHelpEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        public static string NoTasksHelpStart {
            get {
                return ResourceManager.GetString("NoTasksHelpStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates live tile..
        /// </summary>
        public static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high priority.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low priority.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal priority.
        /// </summary>
        public static string PriorityNormal {
            get {
                return ResourceManager.GetString("PriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new task.
        /// </summary>
        public static string QuickAddLabel {
            get {
                return ResourceManager.GetString("QuickAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before due date.
        /// </summary>
        public static string ReminderBeforeDueDateText {
            get {
                return ResourceManager.GetString("ReminderBeforeDueDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful restore..
        /// </summary>
        public static string RestoreOk {
            get {
                return ResourceManager.GetString("RestoreOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RestoreText {
            get {
                return ResourceManager.GetString("RestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select items to restore.
        /// </summary>
        public static string RestoreWhatText {
            get {
                return ResourceManager.GetString("RestoreWhatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring.
        /// </summary>
        public static string Restoring {
            get {
                return ResourceManager.GetString("Restoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select backup to restore.
        /// </summary>
        public static string SelectBackup {
            get {
                return ResourceManager.GetString("SelectBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically complete subtasks.
        /// </summary>
        public static string SettingsCompleteSubtasks {
            get {
                return ResourceManager.GetString("SettingsCompleteSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you complete a task that contains subtasks, those subtasks will be automatically marked as completed..
        /// </summary>
        public static string SettingsCompleteSubtasksDetail {
            get {
                return ResourceManager.GetString("SettingsCompleteSubtasksDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default date.
        /// </summary>
        public static string SettingsDefaultDate {
            get {
                return ResourceManager.GetString("SettingsDefaultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings for task tile.
        /// </summary>
        public static string SettingsDefaultTaskTileSettings {
            get {
                return ResourceManager.GetString("SettingsDefaultTaskTileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default time.
        /// </summary>
        public static string SettingsDefaultTime {
            get {
                return ResourceManager.GetString("SettingsDefaultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 1 day.
        /// </summary>
        public static string SettingsDeleteAfterOneDay {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 1 week.
        /// </summary>
        public static string SettingsDeleteAfterOneWeek {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterOneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 3 days.
        /// </summary>
        public static string SettingsDeleteAfterThreeDays {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 2 days.
        /// </summary>
        public static string SettingsDeleteAfterTwoDays {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterTwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 2 weeks.
        /// </summary>
        public static string SettingsDeleteAfterTwoWeeks {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete completed tasks.
        /// </summary>
        public static string SettingsDeleteCompletedTasks {
            get {
                return ResourceManager.GetString("SettingsDeleteCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete in.
        /// </summary>
        public static string SettingsDeleteCompletedTasksDays {
            get {
                return ResourceManager.GetString("SettingsDeleteCompletedTasksDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks are always automatically deleted when the application starts..
        /// </summary>
        public static string SettingsDeleteCompletedTasksInfo {
            get {
                return ResourceManager.GetString("SettingsDeleteCompletedTasksInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string SettingsDeleteNever {
            get {
                return ResourceManager.GetString("SettingsDeleteNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when application closes.
        /// </summary>
        public static string SettingsDeleteWhenStarts {
            get {
                return ResourceManager.GetString("SettingsDeleteWhenStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tile.
        /// </summary>
        public static string SettingsEnableTile {
            get {
                return ResourceManager.GetString("SettingsEnableTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string SettingsFeedback {
            get {
                return ResourceManager.GetString("SettingsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send anonymous usage data to improve this app. Statistics help developer to identify and focus on most frequently used features.
        ///No personal data is being collected.
        ///You can also contact us via email..
        /// </summary>
        public static string SettingsFeedbackHelp {
            get {
                return ResourceManager.GetString("SettingsFeedbackHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of week.
        /// </summary>
        public static string SettingsFirstDayOfWeek {
            get {
                return ResourceManager.GetString("SettingsFirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose first day of week.
        /// </summary>
        public static string SettingsFirstDayOfWeekPickerHeader {
            get {
                return ResourceManager.GetString("SettingsFirstDayOfWeekPickerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide task check box.
        /// </summary>
        public static string SettingsHideTaskCheckBox {
            get {
                return ResourceManager.GetString("SettingsHideTaskCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use right to left swipe gesture instead to complete task..
        /// </summary>
        public static string SettingsHideTaskCheckBoxHelp {
            get {
                return ResourceManager.GetString("SettingsHideTaskCheckBoxHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the App list, tap and hold the {0} app, and then tap Pin to start..
        /// </summary>
        public static string SettingsPinTile {
            get {
                return ResourceManager.GetString("SettingsPinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show &quot;add task&quot; text box on main page.
        /// </summary>
        public static string SettingsShowQuickAddTextBox {
            get {
                return ResourceManager.GetString("SettingsShowQuickAddTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show task count.
        /// </summary>
        public static string SettingsShowTaskCount {
            get {
                return ResourceManager.GetString("SettingsShowTaskCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swap title and date on wide tile.
        /// </summary>
        public static string SettingsSwapDateAndTitle {
            get {
                return ResourceManager.GetString("SettingsSwapDateAndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiles.
        /// </summary>
        public static string SettingsTile {
            get {
                return ResourceManager.GetString("SettingsTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin tile upon completion of task.
        /// </summary>
        public static string SettingsUnpinCompleted {
            get {
                return ResourceManager.GetString("SettingsUnpinCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        public static string SettingsVibrate {
            get {
                return ResourceManager.GetString("SettingsVibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not signed in..
        /// </summary>
        public static string SignedInNo {
            get {
                return ResourceManager.GetString("SignedInNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re signed in as {0}..
        /// </summary>
        public static string SignedInYes {
            get {
                return ResourceManager.GetString("SignedInYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in.
        /// </summary>
        public static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a subtask.
        /// </summary>
        public static string SubtaskAdd {
            get {
                return ResourceManager.GetString("SubtaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtasks.
        /// </summary>
        public static string SubtasksText {
            get {
                return ResourceManager.GetString("SubtasksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtask.
        /// </summary>
        public static string SubtaskText {
            get {
                return ResourceManager.GetString("SubtaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string TasksText {
            get {
                return ResourceManager.GetString("TasksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        public static string TaskText {
            get {
                return ResourceManager.GetString("TaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quick add tile.
        /// </summary>
        public static string TileForQuickAddLabel {
            get {
                return ResourceManager.GetString("TileForQuickAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string TileForQuickAddPinButton {
            get {
                return ResourceManager.GetString("TileForQuickAddPinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string TileForQuickAddUnpinButton {
            get {
                return ResourceManager.GetString("TileForQuickAddUnpinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background opacity.
        /// </summary>
        public static string TileSettingsBackgroundOpacity {
            get {
                return ResourceManager.GetString("TileSettingsBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide due date.
        /// </summary>
        public static string TileSettingsHideDate {
            get {
                return ResourceManager.GetString("TileSettingsHideDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide title.
        /// </summary>
        public static string TileSettingsHideTitle {
            get {
                return ResourceManager.GetString("TileSettingsHideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font size.
        /// </summary>
        public static string TileSettingsLineHeight {
            get {
                return ResourceManager.GetString("TileSettingsLineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string TileSettingsPreview {
            get {
                return ResourceManager.GetString("TileSettingsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show completed subtasks.
        /// </summary>
        public static string TileSettingsShowCompletedSubtasks {
            get {
                return ResourceManager.GetString("TileSettingsShowCompletedSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title on one line.
        /// </summary>
        public static string TileSettingsTitleOnOneLine {
            get {
                return ResourceManager.GetString("TileSettingsTitleOnOneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        public static string Time15mins {
            get {
                return ResourceManager.GetString("Time15mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 hours.
        /// </summary>
        public static string Time18hours {
            get {
                return ResourceManager.GetString("Time18hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string Time1day {
            get {
                return ResourceManager.GetString("Time1day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string Time1hour {
            get {
                return ResourceManager.GetString("Time1hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week.
        /// </summary>
        public static string Time1week {
            get {
                return ResourceManager.GetString("Time1week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string Time30mins {
            get {
                return ResourceManager.GetString("Time30mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        public static string Time5mins {
            get {
                return ResourceManager.GetString("Time5mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afternoon.
        /// </summary>
        public static string TimeAfternoon {
            get {
                return ResourceManager.GetString("TimeAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evening.
        /// </summary>
        public static string TimeEvening {
            get {
                return ResourceManager.GetString("TimeEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to late morning.
        /// </summary>
        public static string TimeLateMorning {
            get {
                return ResourceManager.GetString("TimeLateMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morning.
        /// </summary>
        public static string TimeMorning {
            get {
                return ResourceManager.GetString("TimeMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        public static string TimeNight {
            get {
                return ResourceManager.GetString("TimeNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noon.
        /// </summary>
        public static string TimeNoon {
            get {
                return ResourceManager.GetString("TimeNoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in due time.
        /// </summary>
        public static string TimeZero {
            get {
                return ResourceManager.GetString("TimeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string TitleUntitled {
            get {
                return ResourceManager.GetString("TitleUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} week.
        /// </summary>
        public static string Weeks1 {
            get {
                return ResourceManager.GetString("Weeks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks.
        /// </summary>
        public static string Weeks2To4 {
            get {
                return ResourceManager.GetString("Weeks2To4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
