//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTasks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTasks.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string AboutContactUs {
            get {
                return ResourceManager.GetString("AboutContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for {0} {1}.
        /// </summary>
        public static string AboutEmailSubject {
            get {
                return ResourceManager.GetString("AboutEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate application.
        /// </summary>
        public static string AboutRateReview {
            get {
                return ResourceManager.GetString("AboutRateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate.
        /// </summary>
        public static string AppBarActivate {
            get {
                return ResourceManager.GetString("AppBarActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add bullet.
        /// </summary>
        public static string AppBarAddBullet {
            get {
                return ResourceManager.GetString("AppBarAddBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        public static string AppBarComplete {
            get {
                return ResourceManager.GetString("AppBarComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AppBarDelete {
            get {
                return ResourceManager.GetString("AppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all tasks.
        /// </summary>
        public static string AppBarDeleteAll {
            get {
                return ResourceManager.GetString("AppBarDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete completed tasks.
        /// </summary>
        public static string AppBarDeleteCompleted {
            get {
                return ResourceManager.GetString("AppBarDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string AppBarDone {
            get {
                return ResourceManager.GetString("AppBarDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string AppBarNew {
            get {
                return ResourceManager.GetString("AppBarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string AppBarOk {
            get {
                return ResourceManager.GetString("AppBarOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string AppBarPin {
            get {
                return ResourceManager.GetString("AppBarPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin tile.
        /// </summary>
        public static string AppBarPinTile {
            get {
                return ResourceManager.GetString("AppBarPinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string AppBarUnpin {
            get {
                return ResourceManager.GetString("AppBarUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin tile.
        /// </summary>
        public static string AppBarUnpinTile {
            get {
                return ResourceManager.GetString("AppBarUnpinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bullet.
        /// </summary>
        public static string BulletText {
            get {
                return ResourceManager.GetString("BulletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;2.0.0&quot;: {
        ///    &quot;date&quot;: &quot;2014-06-17&quot;,
        ///    &quot;items&quot;: [
        ///      &quot;pin a separate tile of task to the start screen&quot;,
        ///      &quot;simple bulleted list in detail&quot;,
        ///      &quot;quick completion of a task&quot;,
        ///      &quot;redesigned reminder time picker&quot;,
        ///      &quot;bug fixes&quot;,
        ///      &quot;minor changes in design and animation&quot;,
        ///	  &quot;default due date set to \&quot;today\&quot;&quot;,
        ///	  &quot;changelog on \&quot;about\&quot; page&quot;
        ///    ]
        ///  },
        ///  &quot;1.9.7&quot;: {
        ///    &quot;date&quot;: &quot;2014-05-23&quot;,
        ///    &quot;items&quot;: [
        ///      &quot;bug fix (default due date)&quot;
        ///    ]
        ///  },
        ///  &quot;1.9.6&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChangelogFile {
            get {
                return ResourceManager.GetString("ChangelogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE DATE.
        /// </summary>
        public static string ChooseDueDate {
            get {
                return ResourceManager.GetString("ChooseDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose reminder date.
        /// </summary>
        public static string ChooseReminderDate {
            get {
                return ResourceManager.GetString("ChooseReminderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE REMINDER.
        /// </summary>
        public static string ChooseReminderTime {
            get {
                return ResourceManager.GetString("ChooseReminderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE TIME.
        /// </summary>
        public static string ChooseTime {
            get {
                return ResourceManager.GetString("ChooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom due date.
        /// </summary>
        public static string DateCustomDue {
            get {
                return ResourceManager.GetString("DateCustomDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string DateLater {
            get {
                return ResourceManager.GetString("DateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next month.
        /// </summary>
        public static string DateNextMonth {
            get {
                return ResourceManager.GetString("DateNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next week.
        /// </summary>
        public static string DateNextWeek {
            get {
                return ResourceManager.GetString("DateNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no due date.
        /// </summary>
        public static string DateNoDue {
            get {
                return ResourceManager.GetString("DateNoDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string DateOverdue {
            get {
                return ResourceManager.GetString("DateOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someday.
        /// </summary>
        public static string DateSomeday {
            get {
                return ResourceManager.GetString("DateSomeday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this month.
        /// </summary>
        public static string DateThisMonth {
            get {
                return ResourceManager.GetString("DateThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this week.
        /// </summary>
        public static string DateThisWeek {
            get {
                return ResourceManager.GetString("DateThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string DateToday {
            get {
                return ResourceManager.GetString("DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string DateTomorrow {
            get {
                return ResourceManager.GetString("DateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upcoming.
        /// </summary>
        public static string DateUpcoming {
            get {
                return ResourceManager.GetString("DateUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all tasks?.
        /// </summary>
        public static string DeleteAllTasks {
            get {
                return ResourceManager.GetString("DeleteAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all tasks.
        /// </summary>
        public static string DeleteAllTasksCaption {
            get {
                return ResourceManager.GetString("DeleteAllTasksCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        public static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        public static string DeleteTaskCaption {
            get {
                return ResourceManager.GetString("DeleteTaskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DeleteTaskNo {
            get {
                return ResourceManager.GetString("DeleteTaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteTaskYes {
            get {
                return ResourceManager.GetString("DeleteTaskYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task title..
        /// </summary>
        public static string MissingTitle {
            get {
                return ResourceManager.GetString("MissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no reminder.
        /// </summary>
        public static string NoReminder {
            get {
                return ResourceManager.GetString("NoReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks are completed..
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates live tile..
        /// </summary>
        public static string PeriodicTaskDescription {
            get {
                return ResourceManager.GetString("PeriodicTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high priority.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low priority.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal priority.
        /// </summary>
        public static string PriorityNormal {
            get {
                return ResourceManager.GetString("PriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task reminder.
        /// </summary>
        public static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default date.
        /// </summary>
        public static string SettingsDefaultDate {
            get {
                return ResourceManager.GetString("SettingsDefaultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default time.
        /// </summary>
        public static string SettingsDefaultTime {
            get {
                return ResourceManager.GetString("SettingsDefaultTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 1 day.
        /// </summary>
        public static string SettingsDeleteAfterOneDay {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 1 week.
        /// </summary>
        public static string SettingsDeleteAfterOneWeek {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterOneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 3 days.
        /// </summary>
        public static string SettingsDeleteAfterThreeDays {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterThreeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 2 days.
        /// </summary>
        public static string SettingsDeleteAfterTwoDays {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterTwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after 2 weeks.
        /// </summary>
        public static string SettingsDeleteAfterTwoWeeks {
            get {
                return ResourceManager.GetString("SettingsDeleteAfterTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete completed tasks.
        /// </summary>
        public static string SettingsDeleteCompletedTasks {
            get {
                return ResourceManager.GetString("SettingsDeleteCompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete in.
        /// </summary>
        public static string SettingsDeleteCompletedTasksDays {
            get {
                return ResourceManager.GetString("SettingsDeleteCompletedTasksDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks are always automatically deleted when the application starts..
        /// </summary>
        public static string SettingsDeleteCompletedTasksInfo {
            get {
                return ResourceManager.GetString("SettingsDeleteCompletedTasksInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string SettingsDeleteNever {
            get {
                return ResourceManager.GetString("SettingsDeleteNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when application starts.
        /// </summary>
        public static string SettingsDeleteWhenStarts {
            get {
                return ResourceManager.GetString("SettingsDeleteWhenStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tile.
        /// </summary>
        public static string SettingsEnableTile {
            get {
                return ResourceManager.GetString("SettingsEnableTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of week.
        /// </summary>
        public static string SettingsFirstDayOfWeek {
            get {
                return ResourceManager.GetString("SettingsFirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose first day of week.
        /// </summary>
        public static string SettingsFirstDayOfWeekPickerHeader {
            get {
                return ResourceManager.GetString("SettingsFirstDayOfWeekPickerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the App list, tap and hold the Simple Tasks app, and then tap Pin to start..
        /// </summary>
        public static string SettingsPinTile {
            get {
                return ResourceManager.GetString("SettingsPinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile.
        /// </summary>
        public static string SettingsTile {
            get {
                return ResourceManager.GetString("SettingsTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin tile upon completion of task.
        /// </summary>
        public static string SettingsUnpinCompleted {
            get {
                return ResourceManager.GetString("SettingsUnpinCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afternoon.
        /// </summary>
        public static string TimeAfternoon {
            get {
                return ResourceManager.GetString("TimeAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evening.
        /// </summary>
        public static string TimeEvening {
            get {
                return ResourceManager.GetString("TimeEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to late morning.
        /// </summary>
        public static string TimeLateMorning {
            get {
                return ResourceManager.GetString("TimeLateMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morning.
        /// </summary>
        public static string TimeMorning {
            get {
                return ResourceManager.GetString("TimeMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night.
        /// </summary>
        public static string TimeNight {
            get {
                return ResourceManager.GetString("TimeNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noon.
        /// </summary>
        public static string TimeNoon {
            get {
                return ResourceManager.GetString("TimeNoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
