//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.AboutDataSource
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class AboutDataSource { }
#else

	public class AboutDataSource : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public AboutDataSource()
		{
			try
			{
				Uri resourceUri = new Uri("/SimpleTasks;component/SampleData/AboutDataSource/AboutDataSource.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private string _VersionString = string.Empty;

		public string VersionString
		{
			get
			{
				return this._VersionString;
			}

			set
			{
				if (this._VersionString != value)
				{
					this._VersionString = value;
					this.OnPropertyChanged("VersionString");
				}
			}
		}
	}
#endif
}
